// AI providers (OpenAI-compatible endpoints). Free-tier quotas audited per the
// 2026-09-02/03 research doc (Free Tiers & Free-Token Budget v3.8.50).
// Shared by the settings Providers tab and the AI assistant tab.
export interface AiProvider {
  id: string;
  label: string;
  desc: string;
  baseUrl: string;
  model: string;
  keyHint: string;
  placeholder: string;
  group: "free" | "credit" | "paid";
  color: string;
  letter: string;
  tos?: "caution" | "ok";
  tosNote?: string;
}

export const AI_PROVIDERS: AiProvider[] = [
  {
    id: "openrouter",
    label: "OpenRouter",
    desc: "موديلات :free — 50 طلب/يوم (20/دقيقة) — 1K/يوم بإيداع $10",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "meta-llama/llama-3.3-70b-instruct:free",
    keyHint: "انسخ مفتاحك من openrouter.ai/keys (تنسيق sk-or-...). الموديلات المجانية تعمل حتى بدون مفتاح.",
    placeholder: "sk-or-...",
    group: "free",
    color: "#6B7FE7",
    letter: "OR",
    tos: "caution",
    tosNote: "يمنع إعادة بيع الوصول أو تطوير خدمة منافسة — الاستخدام الشخصي الذاتي مقبول.",
  },
  {
    id: "groq",
    label: "Groq",
    desc: "حصة يومية لكل موديل (200K توكن/يوم) — بدون بطاقة",
    baseUrl: "https://api.groq.com/openai/v1",
    model: "llama-3.1-8b-instant",
    keyHint: "أنشئ مفتاحك من console.groq.com/keys (مجاني، بدون بطاقة). llama-3.1-8b: 14,400 طلب/يوم.",
    placeholder: "gsk_...",
    group: "free",
    color: "#F55036",
    letter: "G",
    tos: "caution",
    tosNote: "يمنع إعادة البيع أو توزيع الوصول لطرف ثالث.",
  },
  {
    id: "google",
    label: "Google AI Studio",
    desc: "Gemini Flash — عائلة Flash فقط (2.0 اتقفت 2026-06)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    model: "gemini-2.5-flash",
    keyHint: "أنشئ مفتاحك من aistudio.google.com/apikey (مجاني، بدون بطاقة). حدود يومية انخفضت 50-80%.",
    placeholder: "AIza...",
    group: "free",
    color: "#4285F4",
    letter: "G",
    tos: "caution",
    tosNote: "الطبقة المجانية للتطوير — بياناتك تُستخدم للتدريب خارج EU/UK/CH.",
  },
  {
    id: "nara",
    label: "NaraRouter",
    desc: "7M توكن/يوم — 15 طلب/دقيقة — بدون بطاقة",
    baseUrl: "https://router.bynara.id/v1",
    model: "nemotron-3-super-free",
    keyHint: "أنشئ مفتاحك من router.bynara.id (خطة Free: 7M توكن/يوم بـ 12 موديل — بدون بطاقة).",
    placeholder: "مفتاحك...",
    group: "free",
    color: "#0EA5E9",
    letter: "NR",
    tos: "caution",
    tosNote: "يمنع إعادة البيع أو الاستخدام المنافس.",
  },
  {
    id: "llm7",
    label: "LLM7",
    desc: "~150M توكن/شهر — 40 طلب/دقيقة (200 طلب/ساعة)",
    baseUrl: "https://api.llm7.io/v1",
    model: "gemini-3-flash",
    keyHint: "احصل على توكن مجاني من token.llm7.io (صار التسجيل مطلوباً).",
    placeholder: "توكنك...",
    group: "free",
    color: "#A855F7",
    letter: "L",
    tos: "caution",
    tosNote: "مخصص للتجريب والتطوير والبحث — بدون حظر صريح للوكيل الشخصي.",
  },
  {
    id: "sambanova",
    label: "SambaNova",
    desc: "20 طلب/دقيقة، 200K توكن/يوم + كريدت $5",
    baseUrl: "https://api.sambanova.ai/v1",
    model: "Meta-Llama-3.3-70B-Instruct",
    keyHint: "أنشئ مفتاحك من cloud.sambanova.ai (كريدت $5 — صالح 3 أشهر + طبقة مجانية دائمة).",
    placeholder: "مفتاحك...",
    group: "free",
    color: "#F97316",
    letter: "SN",
    tos: "caution",
    tosNote: "يمنع إعادة البيع أو إتاحة الخدمة للغير.",
  },
  {
    id: "nvidia",
    label: "NVIDIA NIM",
    desc: "تجريبي/تطوير فقط — 40 طلب/دقيقة",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    model: "meta/llama-3.3-70b-instruct",
    keyHint: "أنشئ مفتاحك من build.nvidia.com (يتطلب تحقق برقم الهاتف — 1K كريدت تسجيل).",
    placeholder: "nvapi-...",
    group: "free",
    color: "#76B900",
    letter: "N",
    tos: "caution",
    tosNote: "للتجريب/التطوير/التقييم فقط — الإنتاج (خدمة مستخدمين فعليين) يتطلب اتفاق.",
  },
  {
    id: "mistral",
    label: "Mistral",
    desc: "1B توكن/شهر مجاناً — 1 طلب/ثانية (مُوثّق)",
    baseUrl: "https://api.mistral.ai/v1",
    model: "mistral-small-latest",
    keyHint: "أنشئ مفتاحك من console.mistral.ai (يتطلب موافقة على تدريب البيانات).",
    placeholder: "مفتاحك...",
    group: "free",
    color: "#FF7000",
    letter: "M",
    tos: "caution",
    tosNote: "للاحتياجات الشخصية فقط — يمنع إتاحة المفاتيح للغير.",
  },
  {
    id: "zai",
    label: "ZAI (GLM)",
    desc: "GLM-4.7-Flash مجاني دائم — 200K سياق + 20M تسجيل",
    baseUrl: "https://api.z.ai/api/paas/v4",
    model: "glm-4.7-flash",
    keyHint: "أنشئ مفتاحك من z.ai (ZAI_API_KEY — حصة مجانية كريمة + 20M كريدت تسجيل).",
    placeholder: "مفتاحك...",
    group: "free",
    color: "#3E5BFF",
    letter: "Z",
    tos: "ok",
    tosNote: "مجاني دائم — بدون قيود واضحة على الاستخدام الشخصي.",
  },
  {
    id: "siliconflow",
    label: "SiliconFlow",
    desc: "موديلات $0 دائمة (Qwen) — uncapped + $1 تجريبية",
    baseUrl: "https://api.siliconflow.cn/v1",
    model: "Qwen/Qwen2.5-7B-Instruct",
    keyHint: "أنشئ مفتاحك من cloud.siliconflow.cn (مجاني — موديلات $0 دائمة).",
    placeholder: "sk-...",
    group: "free",
    color: "#6E56F8",
    letter: "S",
    tos: "caution",
    tosNote: "يمنع إتاحة الخدمة لأي طرف ثالث أو إعادة البيع.",
  },
  {
    id: "cerebras",
    label: "Cerebras",
    desc: "كريدت $5 مرة واحدة — يتطلب بطاقة (30 يوم)",
    baseUrl: "https://api.cerebras.ai/v1",
    model: "llama-3.1-8b",
    keyHint: "أنشئ حسابك من cloud.cerebras.ai (كريدت ترحيبي $5 مرة واحدة — يتطلب طريقة دفع، صلاحية 30 يوم).",
    placeholder: "csk-...",
    group: "credit",
    color: "#F2D024",
    letter: "C",
    tos: "caution",
    tosNote: "يمنع إعادة البيع — الاستخدام الشخصي/التجاري غير المصرح محظور.",
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    desc: "كريدت ~1M مرة واحدة — يتطلب بطاقة",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    model: "meta-llama/Llama-3.3-70B-Instruct",
    keyHint: "أنشئ مفتاحك من deepinfra.com (يتطلب بطاقة/دفع مسبق — كريدت ترحيبي ~1M مرة واحدة).",
    placeholder: "مفتاحك...",
    group: "credit",
    color: "#14B8A6",
    letter: "D",
    tos: "caution",
    tosNote: "يمنع الاستخدام المنافس مباشرة أو بشكل غير مباشر.",
  },
  {
    id: "openai",
    label: "OpenAI",
    desc: "المدفوع — GPT-4o/5",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4o-mini",
    keyHint: "انسخ مفتاحك من platform.openai.com/api-keys (يتطلب رصيد).",
    placeholder: "sk-proj-...",
    group: "paid",
    color: "#10A37F",
    letter: "AI",
  },
];
